# Generated by Django 3.0.4 on 2021-07-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_garde',
            name='type_transport',
        ),
        migrations.AddField(
            model_name='service_garde',
            name='type_cantine',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('AM-PM', 'AM-PM'), ('Mercredi PM', 'Mercredi PM')], max_length=100, null=True),
        ),
    ]
