# Generated by Django 3.0.4 on 2021-07-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_auto_20210710_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantine',
            name='type_transport',
        ),
        migrations.AddField(
            model_name='cantine',
            name='type_cantine',
            field=models.CharField(choices=[('4j', '4j'), ('5j', '5j'), ('NON', 'NON')], max_length=100, null=True),
        ),
    ]
