# Generated by Django 3.0.4 on 2021-07-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_auto_20210710_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='date_naissance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
