# Generated by Django 3.0.4 on 2021-07-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_enfant_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='assure',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=100, null=True),
        ),
    ]
